WebApplication1/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Context;
using WebApplication1.Models;
using System.Dynamic;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            dynamic data = new ExpandoObject();
            data.Category = category;
            data.Products = db.Products.Where(p => p.CategoryId == category.Id).ToList();
            return View(data);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/CategoryOld/Create.cshtml
@{
    @model WebApplication1.Models.Category

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Form nhap du lieu cho Category</h2>
@{ Html.BeginForm();}
<div class="form-horizontal">
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(Model => Model.Name, htmlAttributes: new { @class="control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(Model => Model.Name, new { htmlAttributes = new {@class = "form-control" }})
            @Html.ValidationMessageFor(Model => Model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(Model => Model.Image, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(Model => Model.Image, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(Model => Model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(Model => Model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(Model => Model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </div>
</div>

@{ Html.EndForm();}

WebApplication1/Views/CategoryOld/Index.cshtml
@{
    @model WebApplication1.Models.Category

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h1>
    @ViewData["Message"]
</h1>
<h2>Times: @ViewData["CurrentTime"]</h2>

<h2>dung voi dang viewbag</h2>

<h3>
    @ViewBag.Message
</h3>
<p>
    @ViewBag.CurrentTime
</p>
@{ 
    //day la noi viet code C#
    var products = new string[] { "laptop", "PC", "Telephone" };
}
<ul>
    @foreach (var product in products)
    {
                <li>Product: @product</li>
    }
</ul>
<a href="~/Home/About">About Us</a><br/>
@Html.ActionLink("Home", "Index", "Home")

<h2>Start Form Login</h2>
@{Html.BeginForm("Create", "Category");}
    @Html.Label("Email")
    @Html.TextBox("email")<br/>
    
    @Html.Label("Password")
    @Html.Password("password")<br/>

    @Html.DropDownList("city", new SelectList(new[] {"Ha Noi", "Sai Gon"}),"Chon Tinh/Thanh Pho")<br />

    @Html.RadioButton("gender","male",true)Nam<br />
    @Html.RadioButton("gender", "female")Nu<br />

    @Html.CheckBox("Rememmber")
    @Html.Label("Remember me")<br />

    <button type="submit">Submit</button>
@{Html.EndForm();}
<br />
<h3>Thong tin danh muc</h3>
<h3>Ten: @Model.Name</h3>
<h3>Anh: @Model.Image</h3>
<h3>Mo ta: @Model.Description</h3>