WebApplication1/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Cart
    {
        public Customer customer;
        public List<CartItem> cartItems;
        public decimal grandTotal;

        public Cart()
        {
            cartItems = new List<CartItem>();
        }
        public List<CartItem> CartItems { get => cartItems; }
        public decimal GrandTotal { get => grandTotal; set => grandTotal = value; }
        public Customer Customer { get => customer; set => customer = value; }

        public CartItem this[int index]
        {
            get => CartItems[index];
            set => CartItems[index] = value;
        }

        public bool AddToCart(CartItem item)
        {
            //kiem tra xem co san pham chua???
            int check = CheckExists(item);
            if (check >= 0)
            {
                CartItems[check].Quantity += item.Quantity;
            }
            else
            {
                CartItems.Add(item);
            }
            CaculateGrandTotal();
            return true;
        }
        public void RemoveItem(int id)
        {
            foreach (var item in CartItems)
            {
                if (item.Product.Id == id)
                {
                    CartItems.Remove(item);
                    CaculateGrandTotal();
                    return;
                }
            }
        }
        //ham kiem tra xem co sp chua
        public int CheckExists(CartItem item)
        {
            for(int i = 0; i< CartItems.Count; i++)
            {
                if(CartItems[i].Product.Id == item.Product.Id)
                {
                    return i;
                }
            }
            return -1;
        }
        public void CaculateGrandTotal()
        {
            decimal grand = 0;
            foreach(CartItem item in CartItems)
            {
                grand += item.Product.Price * item.Quantity;
            }
            GrandTotal = grand;
        }
    }
}

WebApplication1/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }

        public int CategoryId { get; set; }
        public int BrandId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Brand Brand { get; set; }

    }
}

WebApplication1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Context;
using WebApplication1.Models;
using System.Dynamic;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Product
        public ActionResult Index(string search, string sortOrder, string categoryId)
        {
            ViewBag.CategoryId = 0;
            string sort = !string.IsNullOrEmpty(sortOrder) ? sortOrder : "asc";


            //cach 1 dung thang dbSet
            //if (!string.IsNullOrEmpty(search))
            //{
            //    var products = db.Products.Where(p => p.Name.Contains(search)).OrderBy(p=> p.Name).ToList();
            //    return View(products);
            //}

            //return View(db.Products.OrderBy(p => p.Name).ToList());

            //cach 2 dung dbRaw
            var products = from p in db.Products select p;
            if (!string.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search));
            }
            switch (sort)
            {
                case "asc": products = products.OrderBy(p => p.Name);
                    break;
                case "desc": products = products.OrderByDescending(p => p.Name);
                    break;
            }
            // loc theo category
            if (!string.IsNullOrEmpty(categoryId))
            {
                var catId = Convert.ToInt32(categoryId);
                products = products.Where(p => p.CategoryId == catId);
                ViewBag.CategoryId = catId;
            }


            var categories = db.Categories.ToList();
            dynamic data = new ExpandoObject();
            data.Products = products;
            data.Categories = categories;
            return View(data);
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult AddToCart(int? id, int? qty)
        {
            try
            {
                Product product = db.Products.Find(id);
                if(product == null)
                {
                    return HttpNotFound();
                }
                //them vao gio hang
                CartItem item = new CartItem(product, (int)qty);
                //lay gio hang tu session
                Cart cart = (Cart)Session["Cart"];
                if (cart == null)
                {
                    Customer customer = new Customer("Nguyen Van A", "0123456789", "8A Ton That Thuyet");
                    cart = new Cart();
                }
                cart.AddToCart(item);
                Session["cart"] = cart;
            }
            catch(Exception)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Cart");
        }
        public ActionResult RemoveItem(int? id)
        {
            try
            {

                Cart cart = (Cart)Session["Cart"];
                if (cart == null)
                {
                    return HttpNotFound();
                }
                cart.RemoveItem((int)id);
                Session["cart"] = cart;// theem session
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Cart");
        }

        public ActionResult Cart()
        {
            return View();
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "id", "BrandName");
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image,Price,Description,CategoryId,BrandId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "id", "BrandName", product.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "id", "BrandName", product.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image,Price,Description,CategoryId,BrandId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "id", "BrandName", product.BrandId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CheckOut(Order order)
        {
            if (ModelState.IsValid)
            {
                var cart = (Cart)Session["cart"];
                order.GrandTotal = cart.GrandTotal;
                order.CreatedAt = DateTime.Now;
                order.Status = 1;
                db.Orders.Add(order);
                db.SaveChanges();

                foreach(var item in cart.cartItems)
                {
                    OrderItem orderItem = new OrderItem() { OrderID = order.Id, ProductID = item.Product.Id, Qty = item.Quantity, Price = item.Product.Price };
                    db.OrderItems.Add(orderItem);
                }
                db.SaveChanges();
                Session["cart"] = null; //xoa gio hang sau khi order
            }

            return Redirect("http://sandbox.vnpayment.vn/tryitnow/Home/CreateOrder");
        }
        public string CheckoutSuccess()
        {
            return "Create order successfully!";
        }
    }
}

WebApplication1/Views/Product/Cart.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    WebApplication1.Models.Cart cart = Session["cart"] != null ? (WebApplication1.Models.Cart)Session["cart"] : new WebApplication1.Models.Cart();
}

<h2>Giỏ hàng</h2>
@if(cart.CartItems.Count > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên sản phẩm</th>
                            <th>Đơn giá</th>
                            <th>Số lượng</th>
                            <th>Thành tiền</th>
                            <th></th>
                        </tr>
                    </thead>
                        <tbody>
                            @foreach (var item in cart.CartItems)
                            {
                                decimal total = item.Quantity * item.Product.Price;
                            <tr>
                                <td>@item.Product.Id</td>
                                <td>@item.Product.Name</td>
                                <td>@item.Product.Price</td>
                                <td>@item.Quantity</td>
                                <td>@total</td>
                                <td>@Html.ActionLink("Delete", "RemoveItem", new { id = item.Product.Id })</td>
                            </tr>
                            }
                        </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-right" colspan="6">
                                Tổng: <span class="text-danger">@cart.GrandTotal</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-right" colspan="6">
                                <a href="@Url.Action("CheckOut")" class="btn btn-success">Đặt hàng</a>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            }
            else
            {
    <p class="text-danger">Không có sản phẩm nào trong giỏ hàng</p>
            }

WebApplication1/Views/Product/CheckOut.cshtml
@model WebApplication1.Models.Order
@{
    ViewBag.Title = "CheckOut";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    WebApplication1.Models.Cart cart = Session["cart"] != null ? (WebApplication1.Models.Cart)Session["cart"] : new WebApplication1.Models.Cart();
}

<h2>CheckOut</h2>
@if (cart.CartItems.Count > 0)
{
    <div class="row">
        <div class="col-8">
            @{ Html.BeginForm("CreateOrder");}
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Create Order</button>
            </div>
            @{ Html.EndForm();}
        </div>
        <div class="col-4">
            <table class="table">
                <thead>
                    <tr>
                        <th>Product name</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in cart.CartItems)
                    {
                        var sub = item.Quantity * item.Product.Price;
                        <tr>
                            <td>@item.Product.Name</td>
                            <td>@item.Product.Price</td>
                            <td>@item.Quantity</td>
                            <td>@sub</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">Grand Total</td>
                        <td>@cart.GrandTotal</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

}
else
{
    <p>Chưa có sản phẩm để đặt hàng</p>
}

WebApplication1/Views/Product/Create.cshtml
@model WebApplication1.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "Brand", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Product/Delete.cshtml
@model WebApplication1.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Product/Details.cshtml
@model WebApplication1.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.BrandName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
           <img src=" @Html.DisplayFor(model => model.Image)" class="image img-rounded" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Add To Cart", "AddToCart", new { id = Model.Id, qty=1 }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Product/Edit.cshtml
@model WebApplication1.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, "BrandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Product/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    var products = Model;
}

<h2>Index</h2>
@{ Html.BeginForm("Index", "Product", FormMethod.Get);}
    @Html.TextBox("search")
<select name="categoryId" class="form-control">
    <option value="">Select category</option>
    @foreach (WebApplication1.Models.Category item in Model.Categories)
    {
        <option @(ViewBag.CategoryId == item.Id ? "selected" : "") value="@item.Id">@item.Name</option>
    }

</select>
<button type="submit">Search</button>

<p>
    @Html.ActionLink("Create New", "Create") |

    @Html.ActionLink("Sort by name ASC", "Index", new { sortOrder = "asc" }) |
    @Html.ActionLink("Sort by name DESC", "Index", new { sortOrder = "desc" })
</p>
<table class="table table-striped">
    <tr class="table-warning">
        @*<th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>*@
        <th>
            Name
        </th>
        <th>
            Image
        </th>
        <th>
            Price
        </th>
        <th>
            Description
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (WebApplication1.Models.Product item in Model.Products) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Brand.BrandName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            <img class="img-lg img-bordered img-rounded" src="@Html.DisplayFor(modelItem => item.Image)" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>